move "org.camaraproject.geofencing.v0.subscription-ends" out of /subscriptions - request
camaraproject/DeviceLocation pull request #115
Opened 2023-11-14 09:10 UTC by maxl2287

#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:
Removes the event "org.camaraproject.geofencing.v0.subscription-ends" out of the _/subscriptions_ - request.
Only use this event for CloudEvent - callbacks.

#### Which issue(s) this PR fixes:

Fixes #113

2023-11-14 10:33 UTC, bigludo7 approved these changes
LGTM 
Thanks @maxl2287

2023-11-14 15:26 UTC, jlurien requested changes

2023-11-14 15:26 UTC, jlurien commented on code/API_definitions/geofencing.yaml
> +      allOf:
We cannot "extend" an enum this way, as allOf requires compliance to both schemas, and any of the specific values cannot comply with both schemas at the same time. We have to define a new enum with the 3 values, same model as in https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L568

2023-11-15 08:46 UTC, jlurien requested changes

2023-11-15 08:46 UTC, jlurien commented on code/API_definitions/geofencing.yaml
> +        - org.camaraproject.device-status.v0.subscription-ends
```suggestion
        - org.camaraproject.geofencing.v0.subscription-ends
```

2023-11-15 10:02 UTC, jlurien approved these changes
LGTM

2023-11-15 10:07 UTC, bigludo7 approved these changes
LGTM

2023-11-15 19:09 UTC, merged