fix: change description that subscriptionExpireTime is optional #120
camaraproject/DeviceLocation pull request #162
Opened 2024-03-05 21:43 UTC by maxl2287

#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:

Correct the description for "subscription-ends" that this event will be send, when subscription expire time is optionally set by the requester.

#### Which issue(s) this PR fixes:

Fixes #161

2024-03-06 07:27 UTC, bigludo7 approved these changes
Good for me!

2024-03-06 07:54 UTC, alpaycetin74 commented on code/API_definitions/geofencing.yaml
>      This notification did not requires dedicated subscription.
Minor typo here. Should read: "This notification **does not require** dedicated subscription." 
Thank you.

2024-03-06 09:44 UTC, alpaycetin74 approved these changes
LGTM, thank you

2024-03-06 09:46 UTC, bigludo7 approved these changes

2024-03-08 09:38 UTC, jlurien approved these changes
This explanation is more clear now, thanks

2024-03-08 09:41 UTC, jlurien requested changes
Sorry, I didn't realise before that we have to update version to 0.2.0-wip

2024-03-08 10:07 UTC, alpaycetin74 approved these changes
LGTM, thank you

2024-03-08 10:09 UTC, maxl2287 commented
This changes will be included in #163 .
That's why this PR will be closed.

2024-03-08 10:09 UTC, closed without merging